### ISSUE TITLE
Template updates

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Template-Cloud-Workshop#2]
I've gone through all the documents and updated the templates based on emails and for consistency.
 - Added alt-text to the header
 - Made bulleting more consistent
 - Removed periods after bulleted items
 - Updated sentence casing 

Please look through and let me know if the changes are acceptable and I'll merge to the master.

**Comment by hopero929** [comment]
Reviewed and made minor tweaks. Let's remove alt-text from header before merging.

**Comment by DawnmarieDesJardins** [comment]
Removed alt-text from all document headers and merged July 2018 update with master.  Closing issue.
