### ISSUE TITLE
Typo in "Whiteboad design session" folder

### ISSUE THREAD

**Issue by ZoinerTejada** [Microsoft/MCW-Template-Cloud-Workshop#5]
The folder "Whiteboad design session" has a misspelling, it should be Whiteboa**r**d design session.

**Comment by DawnmarieDesJardins** [comment]
Assigned to Walter - not sure how to change file names on main page.

**Comment by waltermyersiii** [comment]
Fixed using command line git as follows:

git clone https://github.com/Microsoft/MCW-Template-Cloud-Workshop.git
git mv "Whiteboad design session" "Whiteboard design session"
git add -u "Whiteboard design session"
git commit -m "Corrected folder name."
git push

Done!
