### ISSUE TITLE
Broken link to the How to Contribute wiki page in the Contributing markdown document

### ISSUE THREAD

**Issue by sadukie** [microsoft/MCW-Template-Cloud-Workshop#6]
**Describe the bug**

The How to Contribute link on the [Contributing page](https://github.com/microsoft/MCW-Template-Cloud-Workshop/blob/main/CONTRIBUTING.md) in the **Contributing Fixes** section is broken.

It should be updated to use this URL: <https://github.com/Microsoft/MCW/wiki/>

**Broken text**

If you are interested in writing code to fix issues, please see [How to Contribute](https://github.com/Microsoft/MSW/wiki/How-to-Contribute) in the wiki.

**Updated text**

If you are interested in writing code to fix issues, please see [How to Contribute](https://github.com/Microsoft/MCW/wiki/How-to-Contribute) in the wiki.

**Comment by DawnmarieDesJardins** [comment]
Corrected the link, closing the issue.  Thank you!
